CONFIG_ZMK_STUDIO_LOCKING=n

# Reduce RAM usage to fit ZMK Studio on ferris_rev02 (16KB SRAM)
CONFIG_LOG=n
CONFIG_CBPRINTF_NANO=y
CONFIG_ZMK_STUDIO_RPC_THREAD_STACK_SIZE=1024
CONFIG_MAIN_STACK_SIZE=256
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=512
CONFIG_ZMK_STUDIO_RPC_TX_BUF_SIZE=32
CONFIG_ZMK_STUDIO_RPC_RX_BUF_SIZE=20
