CONFIG_ZMK_STUDIO_LOCKING=n

# Reduce RAM usage to fit ZMK Studio on ferris_rev02 (16KB SRAM)
CONFIG_LOG=n
CONFIG_CBPRINTF_NANO=y
CONFIG_BT_BUF_ACL_TX_COUNT=2
CONFIG_BT_CONN_TX_MAX=4
CONFIG_ZMK_STUDIO_RPC_THREAD_STACK_SIZE=2048
